all:
	javac -classpath ~/tdroid/tdroid-4.1.1_r6/frameworks/base/services/java/ PConstraint.java
	javac -classpath ~/tdroid/tdroid-4.1.1_r6/frameworks/base/services/java/ TMLogcatTester.java

clean:
	rm -f *.class